
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TextNameClass(object):
    def setupUi(self, TextNameClass):
        TextNameClass.setObjectName("TextNameClass")
        TextNameClass.resize(400, 413)
        TextNameClass.setStyleSheet("\n"
"background-color: rgb(114, 159, 207);")
        #self.btn_second = QtWidgets.QLineEdit(TextNameClass)
        self.push_start = QtWidgets.QPushButton(TextNameClass)
        self.push_start.setGeometry(QtCore.QRect(170,10,75,25))
        self.push_start.setText("Start Time")
        self.push_start.setObjectName("push_start")

        self.push_reset = QtWidgets.QPushButton(TextNameClass)
        self.push_reset.setGeometry(QtCore.QRect(10,360,89,40))
        self.push_reset.setText("Reset")
        self.push_reset.setObjectName("push_reset")

        self.push_next = QtWidgets.QPushButton(TextNameClass)
        self.push_next.setGeometry(QtCore.QRect(290,360,101,41))
        self.push_next.setText("Next")
        self.push_next.setObjectName("push_next")

        self.push_team2 = QtWidgets.QPushButton(TextNameClass)
        self.push_team2.setGeometry(QtCore.QRect(130,380,121,25))
        self.push_team2.setText("Start Team2")
        self.push_team2.setObjectName("push_team2")

        self.btn_second = QtWidgets.QLineEdit(TextNameClass)
        self.btn_second.setGeometry(QtCore.QRect(273, 2, 121, 41))
        font = QtGui.QFont()
        font.setPixelSize(20)
        font.setBold(True)
        self.btn_second.setText("    00:00:00")
        self.btn_second.setFont(font)
        self.btn_second.maxLength()
        self.btn_second.alignment()
        self.btn_second.setReadOnly(True)
        self.btn_second.setStyleSheet("background-color: rgb(245, 121, 0);\n"
"color: rgb(46, 52, 54);")
        self.btn_second.setObjectName("btn_second")
        self.btn_stop = QtWidgets.QPushButton(TextNameClass)
        self.btn_stop.setGeometry(QtCore.QRect(10, 0, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.btn_stop.setFont(font)
        self.btn_stop.setStyleSheet("background-color: rgb(255,69,0);\n"
"color: rgb(46, 52, 54);")
        self.btn_stop.setObjectName("btn_stop")
        self.verticalLayoutWidget = QtWidgets.QWidget(TextNameClass)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 47, 381, 307))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_text1 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        self.btn_text1.setFont(font)
        self.btn_text1.setObjectName("btn_text1")
        self.verticalLayout.addWidget(self.btn_text1)
        self.btn_text2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        self.btn_text2.setFont(font)
        self.btn_text2.setObjectName("btn_text2")
        self.verticalLayout.addWidget(self.btn_text2)
        self.btn_text3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        self.btn_text3.setFont(font)
        self.btn_text3.setObjectName("btn_text3")
        self.verticalLayout.addWidget(self.btn_text3)
        self.btn_text4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        self.btn_text4.setFont(font)
        self.btn_text4.setObjectName("btn_text4")
        self.verticalLayout.addWidget(self.btn_text4)
        self.btn_text5 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        self.btn_text5.setFont(font)
        self.btn_text5.setObjectName("btn_text5")
        self.verticalLayout.addWidget(self.btn_text5)
        self.btn_text6 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        self.btn_text6.setFont(font)
        self.btn_text6.setObjectName("btn_text6")
        self.verticalLayout.addWidget(self.btn_text6)
        self.btn_text7 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        self.btn_text7.setFont(font)
        self.btn_text7.setObjectName("btn_text7")
        self.verticalLayout.addWidget(self.btn_text7)

        self.retranslateUi(TextNameClass)
        QtCore.QMetaObject.connectSlotsByName(TextNameClass)

    def retranslateUi(self, TextNameClass):
        _translate = QtCore.QCoreApplication.translate
        TextNameClass.setWindowTitle(_translate("TextNameClass", "AliasArmenianGame"))
        self.btn_stop.setText(_translate("TextNameClass", "EXIT"))
        self.btn_text1.setText(_translate("TextNameClass", "text"))
        self.btn_text2.setText(_translate("TextNameClass", "text"))
        self.btn_text3.setText(_translate("TextNameClass", "text"))
        self.btn_text4.setText(_translate("TextNameClass", "text"))
        self.btn_text5.setText(_translate("TextNameClass", "text"))
        self.btn_text6.setText(_translate("TextNameClass", "text"))
        self.btn_text7.setText(_translate("TextNameClass", "text"))

